version: 2
jobs:
  test:
    working_directory: /go/src/github.com/raintank/raintank-apps
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: scripts/deps.sh
      - run:
          name: Run go test
          command: go test -v ./...

  qa:
    working_directory: /go/src/github.com/raintank/raintank-apps
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: scripts/deps.sh
      - run:
          name: Formatter
          command: scripts/qa/gofmt.sh
      - run:
          name: Go Generate
          command: scripts/qa/go-generate.sh
      - run:
          name: Check for ineffectual assignments
          command: scripts/qa/ineffassign.sh
      - run:
          name: Check spelling
          command: scripts/qa/misspell.sh
      # Skip unused for now - placeholder code is there on purpose
      #- run:
      #    name: Check for unused code
      #    command: scripts/qa/unused.sh
      # Skip vendor for now
      #- run:
      #    name: Check Vendoring
      #    command: scripts/qa/vendor.sh

  deploy:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Images
          command: scripts/build_docker.sh
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              scripts/deploy_docker.sh
            fi

workflows:
  version: 2
  build_test_qa:
    jobs:
      - test
      - qa
      - deploy:
        requires:
          - test
          - qa
