# use ubuntu image
FROM ubuntu:latest
RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get install -y ca-certificates
#
ENV HOME /app

# Copy the built binaries into /app
RUN mkdir -p /app
COPY --from=raintank/raintank-apps-task-server /app/task-agent-ng /app
RUN mkdir /etc/raintank
COPY ./example-config/task-agent-ng.ini /etc/raintank/task-agent.ini
# Run task-agent
WORKDIR /app
CMD ["./task-agent-ng", "-config", "/etc/raintank/task-agent.ini"]
