{
 "title": "Raintank-Apps Overview",
 "time": { "from": "2018-04-12T18:22:54.113Z", "to": "2018-04-12T18:24:42.755Z" },
 "panels": [
  {
   "title": "TSGW Send Success",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "raintank.apps.stats.taskagent.raintank-apps-task-agent-0.tsdbgw.send.success.counter32"
    }
   ]
  },
  {
   "title": "TSGW Send Success Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "ns",
   "valueName": "current",
   "targets": [
    {
     "target": "raintank.apps.stats.taskagent.raintank-apps-task-agent-0.tsdbgw.send.success.duration_ns.gauge64"
    }
   ]
  },
  {
   "title": "Tasks Active",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "raintank.apps.stats.taskagent.raintank-apps-task-agent-0.runner.tasks.active.gauge32"
    }
   ]
  },
  {
   "title": "Task Server Health",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "raintank.apps.stats.taskserver.*.running.gauge32"
    }
   ]
  },
  {
   "title": "NS1 Collector Durations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "target": "raintank.apps.stats.taskagent.raintank-apps-task-agent-0.collector.ns1.collect.duration_ns.gauge64"
    },
    {
     "target": "raintank.apps.stats.taskagent.raintank-apps-task-agent-0.collector.ns1.collect.success.duration_ns.gauge64"
    }
   ]
  },
  {
   "title": "TSDB Send Failures",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "raintank.apps.stats.taskagent.raintank-apps-task-agent-0.tsdbgw.send.failure.counter32"
    }
   ]
  },
  {
   "title": "TSGW Send Failure Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "format": "ns",
   "valueName": "current",
   "targets": [
    {
     "target": "raintank.apps.stats.taskagent.raintank-apps-task-agent-0.tsdbgw.send.failure.duration_ns.gauge64"
    }
   ]
  },
  {
   "title": "Agents Connected",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "raintank.apps.stats.taskserver.raintank-apps-task-server-0.agent.connections.active.gauge64"
    }
   ]
  },
  {
   "title": "Collector Overview",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "raintank.apps.stats.taskagent.raintank-apps-task-agent-0.collector.ns1.collect.success.counter64"
    },
    {
     "target": "raintank.apps.stats.taskagent.raintank-apps-task-agent-0.collector.ns1.collect.failure.counter64"
    },
    {
     "target": "raintank.apps.stats.taskagent.raintank-apps-task-agent-0.collector.ns1.collect.attempts.counter64"
    }
   ]
  },
  {
   "title": "NS1 Collector Success",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "raintank.apps.stats.taskagent.raintank-apps-task-agent-0.collector.ns1.collect.success.counter64"
    }
   ]
  },
  {
   "title": "NS1 Collector Success Duration",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 8 },
   "format": "ns",
   "valueName": "current",
   "targets": [
    {
     "target": "raintank.apps.stats.taskagent.raintank-apps-task-agent-0.collector.ns1.collect.success.duration_ns.gauge64"
    }
   ]
  },
  {
   "title": "NS1 Collector Failures",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "raintank.apps.stats.taskagent.raintank-apps-task-agent-0.collector.ns1.collect.failure.counter64"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "raintank.apps.ns1.zones.grafana_com.qps"
    }
   ]
  }
 ]
}